package main

import (
	"fmt"
	"net/http"
	// Import Solidity contract bindings generated by abigen or similiar tools
)

func main() {
	http.HandleFunc("/", handler)
	http.ListenAndServe(":8080", nil)
}

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello from the backend!")
}
